const ADD_MENU_ITEM = 'addMenuItem/ADD';
const ADD_MENU_ITEM_GO_BACK = 'addMenuItem/ADD_MENU_ITEM_GO_BACK';
const ADD_MENU_ITEM_NAME = 'addMenuItem/ADD_MENU_ITEM_NAME';
const ADD_MENU_ITEM_PRICE = 'addMenuItem/ADD_MENU_ITEM_PRICE';
const ADD_MENU_ITEM_IMAGE = 'addMenuItem/ADD_MENU_ITEM_IMAGE';
const ADD_MENU_ITEM_DESCRIPTION = 'addMenuItem/ADD_MENU_ITEM_DESCRIPTION';
const ADD_MENU_ITEM_CATEGORY = 'addMenuItem/ADD_MENU_ITEM_CATEGORY';
const ADD_MENU_ITEM_INGREDIENT = 'addMenuItem/ADD_MENU_ITEM_INGREDIENT';
const ADD_MENU_ITEM_CURRENT_INGREDIENTS =
  'addMenuItem/ADD_MENU_ITEM_CURRENT_INGREDIENTS';

const ADD_MENU_ITEM_FETCH_REQUEST = 'addMenuItem/ADD_MENU_ITEM_FETCH_REQUEST';
const ADD_MENU_ITEM_FETCH_SUCCESS = 'addMenuItem/ADD_MENU_ITEM_FETCH_SUCCESS';
const ADD_MENU_ITEM_FETCH_ERROR = 'addMenuItem/ADD_MENU_ITEM_FETCH_ERROR';

const INGREDIENTS_FETCH_REQUEST = 'addMenuItem/INGREDIENTS_FETCH_REQUEST';
const INGREDIENTS_FETCH_SUCCESS = 'addMenuItem/INGREDIENTS_FETCH_SUCCESS';
const INGREDIENTS_FETCH_ERROR = 'addMenuItem/INGREDIENTS_FETCH_ERROR';

export default {
  ADD_MENU_ITEM,
  ADD_MENU_ITEM_GO_BACK,
  ADD_MENU_ITEM_NAME,
  ADD_MENU_ITEM_PRICE,
  ADD_MENU_ITEM_IMAGE,
  ADD_MENU_ITEM_DESCRIPTION,
  ADD_MENU_ITEM_CATEGORY,
  ADD_MENU_ITEM_INGREDIENT,
  ADD_MENU_ITEM_CURRENT_INGREDIENTS,
  ADD_MENU_ITEM_FETCH_REQUEST,
  ADD_MENU_ITEM_FETCH_SUCCESS,
  ADD_MENU_ITEM_FETCH_ERROR,
  INGREDIENTS_FETCH_REQUEST,
  INGREDIENTS_FETCH_SUCCESS,
  INGREDIENTS_FETCH_ERROR,
};
