const ADD_SUCCESS = 'menu/ADD_SUCCESS';
const DELETE_SUCCESS = 'menu/DELETE_SUCCESS';

const CHANGE_FILTER = 'menu/CHANGE_FILTER';

const GET_CATEGORY = 'menu/GET_CATEGORY';
const CHANGE_CATEGORY = 'menu/CHANGE_CATEGORY';
const RESET_CATEGORY = 'menu/RESET_CATEGORY';

const MENU_FETCH_REQUEST = 'menu/FETCH_REQUEST';
const MENU_FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const MENU_FETCH_ERROR = 'menu/FETCH_ERROR';

const CATEGORIES_FETCH_REQUEST = 'categories/FETCH_REQUEST';
const CATEGORIES_FETCH_SUCCESS = 'categories/FETCH_SUCCESS';
const CATEGORIES_FETCH_ERROR = 'categories/FETCH_ERROR';

export default {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  CHANGE_FILTER,
  CHANGE_CATEGORY,
  GET_CATEGORY,
  RESET_CATEGORY,
  MENU_FETCH_REQUEST,
  MENU_FETCH_SUCCESS,
  MENU_FETCH_ERROR,
  CATEGORIES_FETCH_REQUEST,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_FETCH_ERROR,
};
